# Generated by Django 5.0.7 on 2024-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_user_phone_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='asd@asd.com', max_length=255, null=True, unique=True, verbose_name='ادرس ایمیل'),
        ),
    ]
