# Generated by Django 5.0.7 on 2024-07-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=100, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
