# Generated by Django 5.0.7 on 2024-08-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_verifycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
