# Generated by Django 5.0.7 on 2024-08-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otp_delete_verifycode_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.SmallIntegerField(),
        ),
    ]
