# Generated by Django 5.0.7 on 2024-08-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_phone_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/d_profile', null=True, upload_to='profile_image'),
        ),
    ]
