# Generated by Django 5.0.7 on 2024-08-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
