# Generated by Django 5.0.7 on 2024-09-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='product.product')),
            ],
            options={
                'verbose_name': 'محصول ذخیره شده',
                'verbose_name_plural': 'محصولات ذخیره شده',
            },
        ),
    ]
