# Generated by Django 5.0.7 on 2024-09-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_saveproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveProduct',
        ),
    ]
