# Generated by Django 5.0.7 on 2024-08-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
